server {
    listen 80;
    server_name localhost;

    # Directorio raíz donde residen los ficheros compilados
    root /var/www/zensical;
    index index.html index.htm;

    # Resolución de rutas con fallback a 404
    location / {
        try_files $uri $uri/ =404;
    }

    # Bloqueo de seguridad para archivos y carpetas ocultas (.git, etc.)
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    error_page 404 /404.html;
}
